name: aspnet core project template test

on:
  push:
    branches: [ master ]
    paths: 'templates/aspnetcore/**'
  pull_request:
    branches: [ master ]
    paths: 'templates/aspnetcore/**'

defaults:
  run:
    working-directory: templates/aspnetcore

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Test
      run: dotnet test --verbosity normal
